# Generated by Django 3.2.7 on 2021-09-18 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_base', '0001_initial'),
        ('app_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('category_name', models.CharField(max_length=50)),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('img', models.ImageField(upload_to='book_img')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Questions')),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app_main.categorymodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_question', to='app_accounts.customermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_category', to='app_main.categorymodel')),
                ('current_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_owner', to='app_accounts.customermodel')),
                ('imgs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_imgs', to='app_main.imagemodel')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.CreateModel(
            name='AnswersModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('answer', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='Answers')),
                ('votes', models.IntegerField(blank=True, default=0, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='app_main.questionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to='app_accounts.customermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
    ]
