# Generated by Django 3.2.7 on 2021-09-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_base', '0001_initial'),
        ('app_accounts', '0001_initial'),
        ('app_main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPurchasedModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
            ],
            bases=('app_base.basemodel',),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='credit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='imgs',
            field=models.ImageField(blank=True, null=True, upload_to='book_img'),
        ),
        migrations.DeleteModel(
            name='ImageModel',
        ),
        migrations.AddField(
            model_name='bookpurchasedmodel',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchased', to='app_main.bookmodel'),
        ),
        migrations.AddField(
            model_name='bookpurchasedmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_purchased_user', to='app_accounts.customermodel'),
        ),
    ]
