# Generated by Django 3.2.7 on 2021-09-19 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_auto_20210919_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='category',
        ),
    ]
