# Generated by Django 3.2.7 on 2021-09-21 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0002_alter_bookmodel_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
