# Generated by Django 3.2.7 on 2021-09-22 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_accounts', '0001_initial'),
        ('app_base', '0001_initial'),
        ('app_main', '0003_remove_bookmodel_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app_base.basemodel')),
                ('type_of', models.CharField(choices=[('question', 'question'), ('answer', 'answer')], max_length=50)),
                ('linking_id', models.CharField(max_length=1000)),
                ('updownvote', models.CharField(choices=[('up', 'up'), ('down', 'down')], max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voting_user', to='app_accounts.customermodel')),
            ],
            bases=('app_base.basemodel',),
        ),
    ]
