# Generated by Django 3.2.7 on 2021-09-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_bookmodel_for_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
