# Generated by Django 3.2.7 on 2021-09-25 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_bookmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='imgs',
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='is_purchased',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='type_of_book',
            field=models.CharField(choices=[('ebook', 'ebook'), ('hard-copy', 'hard-copy')], default='dsafs', max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_image', to='app_main.bookmodel')),
            ],
        ),
    ]
